### ISSUE TITLE
Finalize the integrations that guard eval & Function.constructor

### ISSUE THREAD

**Issue by koto** [w3c/trusted-types#207]
Essentially, we'd like:
 1. `eval(TrustedScript)`, `new Function(TrustedScript)`, and `new Function(TrustedScript, TrustedScript)` to work
 1.  Their string equivalents to go through the [default policy](https://wicg.github.io/trusted-types/dist/spec/#default-policy-hdr) `createScript` function (a.k.a. if TT are enforced, to generate violation and not execute code by default)
 1.  The default policy to be able to change the values to be executed.

The language primitives tracked in [Dynamic Code Branch Checks](https://github.com/tc39/proposal-dynamic-code-brand-checks) TC39 proposal.

There's additional CSP integration required, tracked #143. Since it relaxes the CSP conditions, we might require a new keyword. We [propose](https://wicg.github.io/trusted-types/dist/spec/#trusted-script-csp-keyword) `script-src 'trusted-script'`

**Comment by koto** [comment]
The Blink/V8 implementation already has the behavior above. The ECMAScript bits are progressing through TC39.

**Comment by koto** [comment]
Note: change the spec text once https://github.com/tc39/proposal-dynamic-code-brand-checks stabilizes. It will likely require adding a slot to `TrustedScript` and adjusting for the new host callout signature - in CSP ( https://w3c.github.io/webappsec-trusted-types/dist/spec/#csp-eval) and HTML.

**Comment by koto** [comment]
The CSP integration would need dynamic-code-brand-checks proposal in ES - that got blocked from advancing to Stage 2 in TC39 ([relevant discussion](https://github.com/tc39/notes/blob/main/meetings/2021-01/jan-26.md#dynamic-host-brand-checks-for-stage-2)), so it's unlikely this would be specified in CSP soon.

**Comment by caridy** [comment]
@koto we got consensus around https://github.com/tc39/ecma262/pull/3222 last week, which I think is related. Now the host hook has access to the value. And we are still pending to figure what to do with https://github.com/tc39/ecma262/pull/1498#issuecomment-1831716341, do you see a path forward there to get this issue folded into it?

**Comment by nicolo-ribaudo** [comment]
Yes. The plenary change was motivated by the desire to expose the string to the host so that CSP's `unsafe-hashes` policy could be extended to work with `eval`/`new Function`. Passing the object as-is doesn't work for this case, because the host would need to stringify the object (which would thus be stringified twice).

My idea is that the hook can still be passed the objects (and it should, for TT, there is no other way), but it can simply receive both the objects and the strings.

**Comment by lukewarlow** [comment]
Given the [Dynamic Code Branch Checks](https://github.com/tc39/proposal-dynamic-code-brand-checks) proposal seems to be stuck at stage 1 it would be good to work out the alternatives.

**Comment by mbrodesser-Igalia** [comment]
> 1. `eval(TrustedScript)`, `new Function(TrustedScript)`, and `new Function(TrustedScript, TrustedScript)` to work

Is actually meant here:

```js
...
let someTrustedScript = somePolicy.createScript("alert(1)");
eval(someTrustedScript);
new Function(someTrustedScript);
```

How does a working example for
```js
Function(TrustedScript, TrustedScript)
```
look like?

**Comment by koto** [comment]
Similarly, i.e. every argument to `Function` constructor is a TrustedScript (created from a policy, or from `fromLiteral`), or a string. 

Proposed [dynamic-code-brand-checks](https://tc39.es/proposal-dynamic-code-brand-checks/) in ES assemble the function body, stringifying all arguments, and tracking whether all were TrustedScripts (using `assembledFromCodeLike` spec variable). 

After assembling, that flag gets passed back to the host, which based on CSP settings, rejects the value and prevents execution, or calls a default TT policy, or allows.

**Comment by mbrodesser-Igalia** [comment]
```js
Function(TrustedScript, TrustedScript)
```
is confusing, because the `Function`'s first argument is not arbitrary script, but a JS parameter. E.g.: https://jsfiddle.net/7cmefw9q/

**Comment by koto** [comment]
Correct, but it can still execute arbitrary JS, and the type to express that capability is `TrustedScript`.

```
let p = trustedTypes.createPolicy("p",
{ createScript: (t) => t });

let ts0 = p.createScript("x = alert(2)");
let ts1 = p.createScript("");


console.log(new Function(ts0, ts1)());
```

**Comment by mbrodesser-Igalia** [comment]
> Correct, but it can still execute arbitrary JS,

No, see e.g. https://jsfiddle.net/aLgctrsn/. MDN might be wrong here (https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/Function#syntax), but presumably it's not arbitrary JS to be executed here. See the spec at https://tc39.es/ecma262/multipage/fundamental-objects.html#sec-function-p1-p2-pn-body which calls https://tc39.es/ecma262/multipage/fundamental-objects.html#sec-createdynamicfunction. Step 10-d-iii of the latter constructs the parameters as a comma separated string of the arguments.

> and the type to express that capability is `TrustedScript`.
> 
> ```
> let p = trustedTypes.createPolicy("p",
> { createScript: (t) => t });
> 
> let ts0 = p.createScript("x = alert(2)");
> let ts1 = p.createScript("");
> 
> 
> console.log(new Function(ts0, ts1)());
> ```

Currently`TrustedScript` (or presumably `TrustedHTML`) needs to  be abused for those parameters. Presumably there could be an alias for `TrustedScript`, e.g. `TrustedFunctionArgument` relying on `new Function()` to fail for wrong input.

**Comment by koto** [comment]
Fair point, i was using the term arbitrary in a colloquial sense, from a security perspective. Function argument declarations can define and/or call other functions, which is XSS-equivalent in Trusted Types context:

```javascript
new Function("a = (()=>{let c = 2; alert(c)})()", "return a")()
```

Technically, this could be represented a different type, but we didn't find a strong reason for it. Similarly `TrustedHTML` is required for both `document.write` and `innerHTML` assignments though different HTML parsers are used in both cases.

**Comment by mbrodesser-Igalia** [comment]
It's a detail and one can reconsider it when a solution for the actual issue of this ticket is found. Updating MDN with an appropriate note might suffice.

Anyway wondering how often `new Function(...)` is used by web-developers.

**Comment by lukewarlow** [comment]
https://github.com/tc39/proposal-dynamic-code-brand-checks/pull/9 - I've started to clean up the dynamic code brand checks proposal repo. This just updates the readme slightly followups will start to touch the spec itself. I can't seem to assign a reviewer (maybe need bug edit permissions?) so posting here.

Thankfully *some* of the changes have already made there way into ecmascript so the spec changes should be more minimal

**Comment by caridy** [comment]
@lukewarlow I think that was always the idea, to give you the compiled code string via `HostEnsureCanCompileStrings`. cc. @nicolo-ribaudo @ptomato

**Comment by lukewarlow** [comment]
@caridy So `HostEnsureCanCompileStrings` now gets a list of parameter strings and the body string, I was hoping we could avoid needing to pass through the compiled string as well but it seems we can't because Chromium already ships with the full string passed through.

`/\(function anonymous\((.*,+.*)\\n\) {\\n(.*)\\n}\)/` - I'm guessing that consumers do something like this regex to extract the parameter list CSV and the body string from the function to actually process? Or is it more a case of just ensuring the string matches verbatim against a whitelist?

Either way I've got a PR that updates the dynamic code proposal to match the current state of the Ecmascript spec to ensure it's kept up to date. Likewise I've made a PR for this spec to follow the updated version.

I'll read through prior discussion on the proposal as to why it didn't get out of stage 1 originally to try and address any if we can. The observable behaviour change from moving the call has already been merged so that should make this proposal less contentious now.

**Comment by lukewarlow** [comment]
> @koto can you link to the issue tracking the addition of the new keyword script-src 'trusted-script'? We will like to see that done sooner rather than later considering the imminent enforcing of the regulations in Europe.

@caridy fyi I've reopened https://github.com/w3c/trusted-types/issues/221 to discuss the use case for a new CSP keyword that allows trusted eval without using the 'unsafe-eval' keyword.

**Comment by ptomato** [comment]
Yes, it probably makes sense to close tc39/ecma262#1498 if there's something that supersedes it.

**Comment by lukewarlow** [comment]
See https://github.com/w3c/trusted-types/issues/461 for discussion about removing default policy handling from eval and co. This is a change that should help make the tc39 change less contentious.

**Comment by lukewarlow** [comment]
https://github.com/tc39/ecma262/pull/3294 - I've opened a draft PR with the changes from the dynamic code brand checks proposal. WIll work on relevant tests needed as well.

**Comment by lukewarlow** [comment]
Closing this as the changes required are largely finalised.
