### ISSUE TITLE
Handle innerHTML of svg in IE

### ISSUE THREAD

**Issue by Siegrift** [w3c/trusted-types#223]
One common pattern that frontend frameworks share is the way they solve a bug in IE, where there is no `innerHTML` of `svg` elements. Frameworks usually solve this in a similar way by creating a  `div` container and using it's `innerHTML` property (e.g [React implementation](https://github.com/facebook/react/blob/b87aabdfe1b7461e7331abb3601d9e6bb27544bc/packages/react-dom/src/client/setInnerHTML.js#L34)).

This breaks under TT, but it's only a very limited case and frameworks might not want to create a policy just for this (e.g. React). Furthermore, this behavior is only present on IE, which will have TT only via polyfill.

I think we can define the `innerHTML` of and svg element to resolve this issue. The usual way frameworks check for it is by checking `'innerHTML' in svgNode`, which would evaulate to `true` and normal assignment would take place and we could use the same checks as we do for `innerHTML` of other elements. I am not 100% sure it would work, but it seems a good thing to do.

**Comment by lukewarlow** [comment]
As IE is now dead and this issue is rather old I'm gonna close it out.
