### ISSUE TITLE
Maybe remove plugin enforcement from Trusted Types?

### ISSUE THREAD

**Issue by shhnjk** [w3c/trusted-types#305]
As Flash and PNaCl went away, I don't see other way of embedding plugins which would cause DOM-XSS or equivalent. While I do see Adobe PDF as another threat, I'm not sure modern browser which supports Trusted Types would allow loading such a plugins.
See also https://github.com/w3c/webappsec-csp/pull/456

**Comment by koto** [comment]
Sounds like it's the time to do it, yes. See also #234. 

// cc @mikewest - Are plugins really, really going away?

**Comment by mikewest** [comment]
Flash is certainly gone. PDF isn't (and I think extensions still support NaCL modules? And possibly something something enterprise policy?). We're in the process of removing `plugin-types` from CSP, but I don't think there's good reason to remove `object-src` yet, given that `<embed>` and `<object>` can certainly still cause code execution.

**Comment by shhnjk** [comment]
> I think extensions still support NaCL modules?

Extensions are not an issue. Content scripts can bypass the Trusted Types anyways.

> given that `<embed>` and `<object>` can certainly still cause code execution.

Causing JS execution isn't an issue, as long as it can't cause a JS execution in the context of the embedder (i.e. parent frame).

**Comment by koto** [comment]
I think Mike was talking about extensions that want to use TT to prevent DOM XSS in their own code.

**Comment by shhnjk** [comment]
Okay, fair :) TT isn't supported in Extensions yet, and I'm waiting for it :)

**Comment by mikewest** [comment]
Why isn't TT supported in extensions? That sounds strange.

**Comment by shhnjk** [comment]
> Why isn't TT supported in extensions? That sounds strange.

There is at least an additional sink available in extension pages (i.e. `chrome.tabs.executeScript`) which needs to be guarded by TT (which isn't yet implemented). I'm waiting for that to be implemented (see [this bug](https://bugs.chromium.org/p/chromium/issues/detail?id=984979#c18)) :)

**Comment by annevk** [comment]
Browser extensions are somewhat explicitly out-of-scope of web platform specifications though. So I don't think that conclusion follows.

**Comment by annevk** [comment]
They are a bit different request-wise, but I'm not sure how much that plays into TT's threat model. I mainly don't want us to make a decision for these elements based on browser extensions.

**Comment by lukewarlow** [comment]
This came back up on my PR to upstream the IDL changes to HTML. If the threat caused by these sinks no longer exists (flash) then I think it makes sense to remove the TT coverage on them?

**Comment by koto** [comment]
+1, we should remove these.
