### ISSUE TITLE
'Create a Trusted Type' algorithm returns error value in step 6 

### ISSUE THREAD

**Issue by smaug----** [w3c/trusted-types#382]
The callbacks return always string (DOMString or USVString), not any kind of error. I think step 6 is supposed to talk about exceptions.

**Comment by Md0135** [comment]
> Geri aramalar herhangi bir hata değil, her zaman dize (DOMString veya USVString) döndürür. 6. adımın istisnalardan bahsetmesi gerektiğini düşünüyorum.
