### ISSUE TITLE
[infra] This repositories GitHub actions are broken

### ISSUE THREAD

**Issue by lukewarlow** [w3c/trusted-types#390]
> [Generate spec](https://github.com/w3c/trusted-types/actions/runs/7489450324/job/20386012928#step:1:38)
Bad request - pnpm/action-setup@v2 is not allowed to be used in w3c/trusted-types. Actions in this workflow must be: within a repository owned by w3c, created by GitHub, or matching the following: w3c/*.

**Comment by mbrodesser-Igalia** [comment]
Related to that https://github.com/w3c/trusted-types/blob/a6096d7ea83c5ce142c941a934b09f241c6b40a4/spec/index.bs#L3 is outdated.
