### ISSUE TITLE
https://github.com/w3c/trusted-types/blob/main/CONTRIBUTING.md requires documentation how to locally generate the spec's HTML

### ISSUE THREAD

**Issue by mbrodesser-Igalia** [w3c/trusted-types#392]
In order to allow locally checking whether a patch is technically correct.

**Comment by mbrodesser-Igalia** [comment]
E.g. to check that references within the spec are correct.

**Comment by lukewarlow** [comment]
If you have [bikeshed](https://speced.github.io/bikeshed/#install-final) installed you can run `cd spec && bikeshed serve --force` from the root of the repo, but I agree it should be documented.
