### ISSUE TITLE
Incorrect assertion within Example 18

### ISSUE THREAD

**Issue by lukewarlow** [w3c/trusted-types#393]
Example 18 states:

> An empty [directive](https://w3c.github.io/webappsec-csp/#directives) [value](https://w3c.github.io/webappsec-csp/#directive-value) indicates policies may not be created, and sinks expect Trusted Type values, i.e. no DOM XSS [injection sinks](https://w3c.github.io/trusted-types/dist/spec/#injection-sink) can be used at all.
Content-Security-Policy: trusted-types; require-trusted-types-for 'script'

However, the `fromLiteral` tagged template function allows you to create a trusted type without any allowed policies afaict. This example should be updated to clarify this.

**Comment by lukewarlow** [comment]
THis might be irellevant depending on #398

**Comment by koto** [comment]
Added a comment to the example. Will remove together with other fromLiteral references, depending on #398.
