### ISSUE TITLE
Integration with WebIDL

### ISSUE THREAD

**Issue by lukewarlow** [w3c/trusted-types#400]
https://w3c.github.io/trusted-types/dist/spec/#webidl-integration - mentions this PR (https://github.com/whatwg/webidl/pull/841)

There's mismatches between what's in this spec and that spec PR.

It would be good if that WebIDL spec PR could be updated with what's in this spec and progressed. We have implementor interest now so that shouldn't be a blocker.

**Comment by mbrodesser-Igalia** [comment]
Integration with WebIDL is necessary, hence setting milestone to v1.

**Comment by lukewarlow** [comment]
Closing as there's no longer any dependency on web idl
