### ISSUE TITLE
Figure out what to do with `script.setAttribute('src')`

### ISSUE THREAD

**Issue by lukewarlow** [w3c/trusted-types#402]
https://w3c.github.io/trusted-types/dist/spec/#setting-slot-values says

> Figure out what to do with script.setAttribute('src'). See [DOM#789](https://github.com/whatwg/dom/issues/789).

We should try to progress that DOM PR as we have renewed implementor interest.

**Comment by mbrodesser-Igalia** [comment]
Setting milestone to v1 since this is required to avoid XSS.

**Comment by lukewarlow** [comment]
@koto does your DOM update address this or should it stay open?

**Comment by koto** [comment]
Yes, you can remove the inline issue too.
