### ISSUE TITLE
Either remove `fromLiteral` from v1 of the spec or add a note to the spec that it'll be implemented later

### ISSUE THREAD

**Issue by mbrodesser-Igalia** [w3c/trusted-types#412]
What's preferred?

Follow-up for https://github.com/w3c/trusted-types/issues/398.

**Comment by lukewarlow** [comment]
I think remove from the spec and make a draft PR to add it back

See https://github.com/w3c/trusted-types/pull/405 for a pull request to remove it

**Comment by lukewarlow** [comment]
https://github.com/web-platform-tests/wpt/pull/44350 - PR to mark test as tentative
