### ISSUE TITLE
CreateXXX as specced can return null values but not marked as such in IDL

### ISSUE THREAD

**Issue by lukewarlow** [w3c/trusted-types#414]
https://w3c.github.io/trusted-types/dist/spec/#create-a-trusted-type-algorithm - returns null or undefined if that's what the default policies functions return and the default policy is being invoked.

But CreateXXX functions on TrustedTypePolicy are marked as returning TrustedHTML without any optionality.

Chromium doesn't ever seem to return null in this case either so I'm slightly confused.

**Comment by koto** [comment]
Good catch again! I think this was lost in one of the refactorings. The behaviour we want is:

- `createXYZ` return a trusted type, or throw. The result value is wrapped in a matching type, so
`trustedTypes.createPolicy('default', {createHTML: () => null}).createHTML('foo')` is a TrustedHTML wrapping `''`.
- when the default policy inner functions (the createXYZ ones defined by the user, held in `[[options]]` slot) return null or undefined, this rejects the value and in turn creates a CSP violation (https://w3c.github.io/trusted-types/dist/spec/#get-trusted-type-compliant-string-algorithm step 6).

The spec currently doesn't follow that. 

I think the best course of action would be to:

1. Add an additional argument to [Create a Trusted Type](https://w3c.github.io/trusted-types/dist/spec/#abstract-opdef-create-a-trusted-type) (e.g. abort on null or undefined?). Only when this flag is present, the null/undefined would be passed to a caller and not be promoted to a Trusted Type in step 6.
2. [Process value with a default policy](https://w3c.github.io/trusted-types/dist/spec/#abstract-opdef-process-value-with-a-default-policy) and only this algorithm sets the flag.

Alternatively, inline the null/undefined-supporting variant of _Create a Trusted Type_ into _Process value with a default policy_?

**Comment by lukewarlow** [comment]
I'm thinking potentially a separate algorithm that returns the raw response from the callback, which the Create a Trusted Type algorithm then wraps in a trusted type. and the default policy algorithm can call the version which returns the raw value and act accordingly?

**Comment by koto** [comment]
That also works :)

**Comment by lukewarlow** [comment]
I've extracted a new "Get Trusted Type policy value" algorithm and moved the stringify and null handling to the respective places in https://github.com/w3c/trusted-types/pull/420 this should fix this issue.
