### ISSUE TITLE
Discrepency between tests and Get Trusted Type Compliant string algorithm

### ISSUE THREAD

**Issue by lukewarlow** [w3c/trusted-types#431]
> 4. Let convertedInput be the result of executing [Process value with a default policy](https://w3c.github.io/trusted-types/dist/spec/#abstract-opdef-process-value-with-a-default-policy) with the same arguments as this algorithm.

> 5. **If the algorithm threw an error, rethrow the error and abort the following steps.**

> 6. If convertedInput is null or undefined, execute the following steps:

- > 1. Let disposition be the result of executing [Should sink type mismatch violation be blocked by Content Security Policy?](https://w3c.github.io/trusted-types/dist/spec/#abstract-opdef-should-sink-type-mismatch-violation-be-blocked-by-content-security-policy) algorithm, passing global, stringified input as source, sinkGroup and sink.

However in https://wpt.live/trusted-types/empty-default-policy.html a `securitypolicyviolation` event is expected to be fired in the event that there's no callback defined for the default policy.  This throws an error which bubbles up and aborts in step 5, preventing this algorithm ever reaching step 6.1 which would dispatch the event.

**Comment by lukewarlow** [comment]
What's the expected behaviour here?

**Comment by koto** [comment]
You're right in both cases. Would changing step 4 in https://w3c.github.io/trusted-types/dist/spec/#abstract-opdef-get-trusted-type-policy-value from:

> If function is null, throw a TypeError.

to

> If function is null, return null

be right here? I think it would.

**Comment by lukewarlow** [comment]
That would break step 2 of https://w3c.github.io/trusted-types/dist/spec/#create-a-trusted-type-algorithm

**Comment by koto** [comment]
I see. Then maybe you can make the https://w3c.github.io/trusted-types/dist/spec/#abstract-opdef-get-trusted-type-policy-value only return the function (renaming the algorithm of course), and steps 4-5 moved to two callers of this algorithm? With step 4 being different for the default policy case.
