### ISSUE TITLE
TrustedTypePolicyFactory getTypeMapping() missing from spec.

### ISSUE THREAD

**Issue by lukewarlow** [w3c/trusted-types#432]
I've just realised Chromium has shipped a method on TrustedTypePolicyFactory that's not specced at all.

The chromium IDL is `object? getTypeMapping(optional DOMString ns);`

This is tested at https://wpt.live/trusted-types/TrustedTypePolicyFactory-metadata.html

Should this be added to the spec for v1 seeing as it's shipped in Chromium or like #384 should we think about removing it?

**Comment by lukewarlow** [comment]
Seems like this was part of https://github.com/w3c/trusted-types/issues/43

**Comment by lukewarlow** [comment]
@koto it would be good if you or someone else from the chromium team could write a PR to the spec with the definition for this method, as it's shipped we made need to keep it and it would be good to have the spec for it ready to go.

**Comment by petervanderbeken** [comment]
When we previously pointed to `getTypeMapping` (and `beforecreatepolicy`) I think the consensus was to remove these, unless there was some significant usage that's blocking this.

**Comment by koto** [comment]
+1. Let's not add `getTypeMapping`, nor `beforecreatepolicy`

**Comment by lukewarlow** [comment]
Going to go ahead and close this as there's no action required from the spec.
