### ISSUE TITLE
Should the "default" policy be called when `setAttributeNode` is called with a node from the same realm?

### ISSUE THREAD

**Issue by mbrodesser-Igalia** [w3c/trusted-types#434]
Example: https://jsfiddle.net/3f2tzusq/2/

Happens currently with Chrome Dev. Presumably it shouldn't.

**Comment by koto** [comment]
Yes. Why do you think it shouldn't? It's in [DOM integration](https://github.com/whatwg/dom/pull/1247) `set an attribute` algorithm (lines 6488-6490 in the current PR).

**Comment by mbrodesser-Igalia** [comment]
> Yes. Why do you think it shouldn't? It's in [DOM integration](https://github.com/whatwg/dom/pull/1247) `set an attribute` algorithm (lines 6488-6490 in the current PR).

Didn't think this through properly before. https://jsfiddle.net/c1noaysw/1/ made me think it shouldn't. However, since `srcdoc` is a`DOMString`, the default policy has to be called.

Perhaps the default policy should be able to distinguish values from the same and a different realm. Would need to think more about that.

**Comment by mbrodesser-Igalia** [comment]
Will open a new ticket for it if necessary,
