### ISSUE TITLE
Issue with script enforcement

### ISSUE THREAD

**Issue by lukewarlow** [w3c/trusted-types#437]
Apologies if I'm missing something but I believe that the spec as currently written blocks any inline script elements from executing.

https://w3c.github.io/trusted-types/dist/spec/#enforcement-in-scripts

A new [[ScriptText]] slot is added and is initially null, this is only every set via the IDL OR when running "prepare the script text" algorithm.

The problem is that the "prepare the script text" algorithm will always throw unless a default policy exists. This means that the test suite for example fails to run.

Chromium I believe has an additional step that parsed script elements set their [[ScriptText]] slot when parsing has finished, this needs speccing.

**Comment by mbrodesser-Igalia** [comment]
> Apologies if I'm missing something but I believe that the spec as currently written blocks any inline script elements from executing.
> 
> https://w3c.github.io/trusted-types/dist/spec/#enforcement-in-scripts
> 
> A new [[ScriptText]] slot is added and is initially null, this is only every set via the IDL OR when running "prepare the script text" algorithm.
> 

That section also mentions "Equivalent to script’s [child text content](https://dom.spec.whatwg.org/#concept-child-text-content). Initially null.". Perhaps "Equivalent to script’s [child text content](https://dom.spec.whatwg.org/#concept-child-text-content)" should be changed to a non-normative note.

> The problem is that the "prepare the script text" algorithm will always throw unless a default policy exists. This means that the test suite for example fails to run.
> 
> Chromium I believe has an additional step that parsed script elements set their [[ScriptText]] slot when parsing has finished, this needs speccing.

**Comment by koto** [comment]
@otherdaniel do you remember how the parser sets the slot value? What algorithm is it a part of?

**Comment by lukewarlow** [comment]
I also don't think the slot can be initially null either.

`data:text/html,<meta http-equiv="Content-Security-Policy" content="require-trusted-types-for 'script'; trusted-types default;"><div id="container"></div><script>const s = document.createElement('script'); container.appendChild(s);</script`

Else something like this would trigger a trusted types violation as it's slot is null and it's child text content is an empty string?

**Comment by lukewarlow** [comment]
So I did some digging and in Chromium it's done in the FinishParsingChildren function

```c++
void HTMLScriptElement::FinishParsingChildren() {
  Element::FinishParsingChildren();

  // We normally expect the parser to finish parsing before any script gets
  // a chance to manipulate the script. However, if script parsing gets
  // deferrred (or similar; see crbug.com/1033101) then a script might get
  // access to the HTMLScriptElement before. In this case, we cannot blindly
  // accept the current TextFromChildren as a parser result.
  DCHECK(children_changed_by_api_ || !script_text_internal_slot_.length());
  if (!children_changed_by_api_)
    script_text_internal_slot_ = ParkableString(TextFromChildren().Impl());
}
```

**Comment by lukewarlow** [comment]
Interestingly the spec is also specifically focused on HTMLScriptElement but the chrome patch also touches SVGScriptElement so some clarity there would be good too.

**Comment by lukewarlow** [comment]
While implementing this in WebKit I'm getting an error where replaceWith is causing a trusted types error that doesn't happen in chromium and that also seems to have other unspecced changes that lead to it. See https://github.com/w3c/trusted-types/issues/438

**Comment by mbrodesser-Igalia** [comment]
> I also don't think the slot can be initially null either.
> 
> `data:text/html,<meta http-equiv="Content-Security-Policy" content="require-trusted-types-for 'script'; trusted-types default;"><div id="container"></div><script>const s = document.createElement('script'); container.appendChild(s);</script`
> 
> Else something like this would trigger a trusted types violation as it's slot is null and it's child text content is an empty string?

Per which part of the spec would that trigger a TT violation?

**Comment by lukewarlow** [comment]
> Per which part of the spec would that trigger a TT violation?

When it's running prepare script text it will compare the inner slot value to the child text contents. Child text contents is always a string so it'd be comparing null to a string, which would then run through the process of trying to put that through the default policy which might not exist (and shouldn't need to for the above to work)

**Comment by mbrodesser-Igalia** [comment]
> > Per which part of the spec would that trigger a TT violation?
> 
> When it's running prepare script text it will compare the inner slot value to the child text contents. Child text contents is always a string so it'd be comparing null to a string, which would then run through the process of trying to put that through the default policy which might not exist (and shouldn't need to for the above to work)

So that's https://w3c.github.io/trusted-types/dist/spec/#prepare-script-text.

> I also don't think the slot can be initially null either.

To overcommunicate: for external scripts (e.g. `<script src=...>`), the `[[ScriptText]]` slot should possibly be null, initially.

**Comment by mbrodesser-Igalia** [comment]
> > > Per which part of the spec would that trigger a TT violation?
> > 
> > 
> > When it's running prepare script text it will compare the inner slot value to the child text contents. Child text contents is always a string so it'd be comparing null to a string, which would then run through the process of trying to put that through the default policy which might not exist (and shouldn't need to for the above to work)
> 
> So that's https://w3c.github.io/trusted-types/dist/spec/#prepare-script-text.
> 
> > I also don't think the slot can be initially null either.
> 
> To overcommunicate: for external scripts (e.g. `<script src=...>`), the `[[ScriptText]]` slot should possibly be null, initially.

Oh, the child text content indeed always is a string (https://dom.spec.whatwg.org/#concept-child-text-content). The empty one for above case.

**Comment by lukewarlow** [comment]
I've made a PR that attempts to add the node manipulation APIs to the spec: https://github.com/w3c/trusted-types/pull/440

The algorithm is slightly unwieldily and I feel like it can probably be simplified so any feedback is very welcome.

**Comment by lukewarlow** [comment]
Related issue: https://github.com/w3c/trusted-types/issues/252

**Comment by lukewarlow** [comment]
Closing this as the parser now at least sets the "script text" value and the null vs empty string issue has been resolved. #525 covers discrepencies between implementation and spec.
