### ISSUE TITLE
https://w3c.github.io/trusted-types/dist/spec/#webidl-validate-the-string-in-context should link to the HTML standard's definition of how the validation is performed

### ISSUE THREAD

**Issue by mbrodesser-Igalia** [w3c/trusted-types#454]
Currently, there's only a note at https://w3c.github.io/trusted-types/dist/spec/#webidl-validate-the-string-in-context linking to the whole HTML standard.

**Comment by mbrodesser-Igalia** [comment]
I've searched for whole word matches of "validate" at https://html.spec.whatwg.org/. 10 results, none corresponds to the definition of "validate the string in context".

**Comment by mbrodesser-Igalia** [comment]
So it's unclear, how the validation is supposed to happen.

**Comment by mbrodesser-Igalia** [comment]
https://w3c.github.io/trusted-types/dist/spec/#html-validate-the-string-in-context is meant.

**Comment by lukewarlow** [comment]
@mbrodesser-Igalia I think it means that it *will* be defined in HTML once it's been upstreamed. The html hash link in TT is the correct algorithm.
