### ISSUE TITLE
Why are `policyOptions` an optional argument of `createPolicy`?

### ISSUE THREAD

**Issue by mbrodesser-Igalia** [w3c/trusted-types#459]
https://w3c.github.io/trusted-types/dist/spec/#trustedtypepolicyfactory

A policy without options is of no use, or?

**Comment by koto** [comment]
I guess it can be used to reject every value? @otherdaniel, can we check if a 2nd argument is actually always passed to `createPolicy`? That seems like worthy of fixing for the API to be more ergonomic.

**Comment by mbrodesser-Igalia** [comment]
Optional is required for technical reasons:
- none of the dictionary's members can be a required member.
- https://webidl.spec.whatwg.org/#ref-for-required-dictionary-member, which contains "If the type of an argument is a [dictionary type](https://webidl.spec.whatwg.org/#idl-dictionary) or a [union type](https://webidl.spec.whatwg.org/#dfn-union-type) that has a [dictionary type](https://webidl.spec.whatwg.org/#idl-dictionary) as one of its [flattened member types](https://webidl.spec.whatwg.org/#dfn-flattened-union-member-types), and that dictionary type and its ancestors have no [required](https://webidl.spec.whatwg.org/#required-dictionary-member) [members](https://webidl.spec.whatwg.org/#dfn-dictionary-member), and the argument is either the final argument or is followed only by [optional arguments](https://webidl.spec.whatwg.org/#dfn-optional-argument), then the argument must be specified as optional and have a default value provided."
