### ISSUE TITLE
Callback IDL types

### ISSUE THREAD

**Issue by lukewarlow** [w3c/trusted-types#482]
Random thought I had while cleaning up some work in WebKit, does it actually make sense for the callbacks to have their own IDL type per callback? Each callback type is identical but currently they're 3 different type defs. Is there any benefit to this? Should we just do `CreateTrustedTypeCallback`?

https://w3c.github.io/trusted-types/dist/spec/#trusted-type-policy-options

**Comment by annevk** [comment]
`CreateScriptURLCallback` has a different return type. But there's no reason for the other two to not be unified.

**Comment by lukewarlow** [comment]
Going to go ahead and close this. There's not much benefit to cutting 3 down to 2, as it wont unify codepaths much
