### ISSUE TITLE
"Create a Trusted Type Policy" should specify the TypeError messages

### ISSUE THREAD

**Issue by mbrodesser-Igalia** [w3c/trusted-types#511]
https://searchfox.org/mozilla-central/rev/0916ef0172ce5b2a72749b659da8ad95f637ef42/testing/web-platform/tests/trusted-types/TrustedTypePolicyFactory-createPolicy-nameTests.html#38 requires that.

https://w3c.github.io/trusted-types/dist/spec/#abstract-opdef-create-a-trusted-type-policy currently not.

**Comment by annevk** [comment]
Hmm, I don't think we should be checked the contents of `message` unless that is somehow required for web compatibility.

**Comment by mbrodesser-Igalia** [comment]
Agreed, it's an implementation detail.

**Comment by lukewarlow** [comment]
@otherdaniel can you comment on whether these messages are important for compatability?

I agree that generally these should be left to the browser to decide. Or these should be specced across the board (way out of scope of this work).
