### ISSUE TITLE
Does the DOM spec really need to special case script elements for replaceChildren etc.

### ISSUE THREAD

**Issue by lukewarlow** [w3c/trusted-types#537]
Currently the [DOM spec](https://dom.spec.whatwg.org/#converting-nodes-into-a-node), and both WebKit and Chromium have special casing in DOM APIs such as node.replaceChildren for script elements. Such that if you try and replace the children with a string or a Text node it would cause a Trusted Types violation.

This was specced in DOM to match the chromium implementation, but was never originally specified in the TT spec.

It's just struck me that this code might be entirely pointless?

Even if you use Trusted types for these APIs they won't set the [script elements internal slot](https://w3c.github.io/trusted-types/dist/spec/#htmlscriptelement-script-text) to actually allow execution. You can also trivially "bypass" them by calling `appendChild(new Text(''))`?

So my question is, why are these implemented in Chromium? Is there something I'm missing or can we drop them from the spec and implementations?

cc @koto @otherdaniel @mbrodesser-Igalia

**Comment by mbrodesser-Igalia** [comment]
> Even if you use Trusted types for these APIs they won't set the script elements internal slot to actually allow execution. You can also trivially "bypass" them by calling appendChild(new Text(''))?

Presumably https://w3c.github.io/trusted-types/dist/spec/#htmlscriptelement-script-text is meant here.

**Comment by lukewarlow** [comment]
> Presumably https://w3c.github.io/trusted-types/dist/spec/#htmlscriptelement-script-text is meant here.

Yeah that's it. Fwiw even the new approach in https://github.com/w3c/trusted-types/pull/533 doesn't change things here.

**Comment by lukewarlow** [comment]
After a bit of investigation it seems this is indeed a left over of a previous model of script enforcement.

https://chromium-review.googlesource.com/c/chromium/src/+/1547746 - July 14th 2019 introduced a similar change to another DOM API (this is no longer in situ)

https://chromium-review.googlesource.com/c/chromium/src/+/1688030 - July 18th 2019 introduced the DOM API handling being discussed.

https://chromium-review.googlesource.com/c/chromium/src/+/1924523 - Dec 2019 introduced current script enforcement model, reverting most of the script checks but forgot the specific ones being discussed.

**Comment by fred-wang** [comment]
@lukewarlow So did you get an answser to your question? I see you reverted your PR, but it is referenced on https://w3c.github.io/trusted-types/dist/spec/#integration-with-dom (will send a PR to remove the link).

**Comment by lukewarlow** [comment]
Ah yeah this issue can be closed once the link to it is dropped from the spec.
