### ISSUE TITLE
WPTs for pre-navigation check of form-submission should be added

### ISSUE THREAD

**Issue by mbrodesser-Igalia** [w3c/trusted-types#549]
See e.g. https://jsfiddle.net/fhrpo2zj/2/.

The spec covers this, since "type" in [1] may be "form-submission" and [2] is fully exercised for that type.

CC @lukewarlow, @otherdaniel 

[1] https://w3c.github.io/webappsec-csp/#should-block-navigation-request
[2] https://w3c.github.io/trusted-types/dist/spec/#require-trusted-types-for-pre-navigation-check

**Comment by mbrodesser-Igalia** [comment]
Adding test is WIP at https://bugzilla.mozilla.org/show_bug.cgi?id=1921008.

**Comment by koto** [comment]
The test seems to be added already, the finals bit in https://github.com/web-platform-tests/wpt/commit/4db7dc692be3aca644252623d69d5db5113541f7. @mbrodesser-Igalia, can this be closed now?
