### ISSUE TITLE
getPropertyType/getAttributeType when null namespaces are passed.

### ISSUE THREAD

**Issue by fred-wang** [w3c/trusted-types#553]
cc @smaug---- @mbrodesser-Igalia @lukewarlow 

`elementNs` and `attrNS` are optional nullable arguments defaulting to the empty string, so we should test what happens when null values are used:

```
optional DOMString? elementNs = ""
optional DOMString? attrNs = ""
```

- For `attrNS`, a null value is explicitly handled in  [Get Trusted Type data for attribute](https://w3c.github.io/trusted-types/dist/spec/#abstract-opdef-get-trusted-type-data-for-attribute). This case is covered by "getAttributeType with full namespace info" cases of `TrustedTypePolicyFactory-getAttributeType-namespace.html` because `attribute.namespaceURI` is null here, but maybe a more explicit test with a null argument would help.

- For `elementNs`, the step retrieving the "element interface for localName and elementNs" is similar to step 7 of [DOM's create an element](https://dom.spec.whatwg.org/#concept-create-element). Probably this is not very explicit, but I understand this falls back to the `Element` interface for null namespace, similarly to [createElementNs(null, "foo")](https://dom.spec.whatwg.org/#internal-createelementns-steps). However, we don't have any tests for that (see #429).

**Comment by fred-wang** [comment]
> For elementNs, the step retrieving the "element interface for localName and elementNs" is similar to step 7 of [DOM's create an element](https://dom.spec.whatwg.org/#concept-create-element). Probably this is not very explicit, but I understand this falls back to the Element interface for null namespace, similarly to [createElementNs(null, "foo")](https://dom.spec.whatwg.org/#internal-createelementns-steps). However, we don't have any tests for that (see https://github.com/w3c/trusted-types/issues/429).

So checking on Chromium and WebKit, an explicitly null elementNs seems to fallback to the HTML namespace.

**Comment by koto** [comment]
This seems to be resolved in the spec via https://github.com/w3c/trusted-types/pull/557, and in WPT via https://github.com/web-platform-tests/wpt/pull/48769. @fred-wang, do you agree this can be closed now?

**Comment by fred-wang** [comment]
Right, we can close it now.
