### ISSUE TITLE
Endless loop of `DOMParser.parseFromString` when used with Trusted Types polyfill

### ISSUE THREAD

**Issue by orazioedoardo** [w3c/trusted-types#563]
_This same issue has been raised at https://github.com/cure53/DOMPurify/issues/1027, but they believe it's not a DOMPurify issue but rather an issue with the polyfill._

### Background & Context

When trying to use DOMPurify in conjunction with the [trustedTypes polyfill](https://www.npmjs.com/package/trusted-types), the HTML is not sanitized but rather seems to run into an endless loop as if DOMPurify does not set its ["dompurify" policy](https://github.com/cure53/DOMPurify/pull/310). Not sure if it's a DOMPurify issue, or an issue with the polyfill, or if I'm using it wrong, sorry if this is the wrong place to ask.

#### Input

This is the sample JavaScript code which then I bundle with webpack.

```
import { trustedTypes, TrustedTypeConfig, TrustedTypesEnforcer } from "trusted-types";
import DOMPurify from "dompurify";

let trustedTypesObject;

if (window.trustedTypes && trustedTypes.createPolicy) {
    trustedTypesObject = window.trustedTypes;
} else {
    trustedTypesObject = trustedTypes;
    const config = new TrustedTypeConfig(false, true, ["default", "dompurify"], false);
    const enforcer = new TrustedTypesEnforcer(config);
    enforcer.install();
}

trustedTypesObject.createPolicy("default", {
    createHTML: (string, type) => {
        console.warn("Created a '" + type + "' object.");
        return DOMPurify.sanitize(string, { RETURN_TRUSTED_TYPE: false });
    },
});
```

#### Given output

Example output from Safari, caught in an endless loop of thousands of `DOMParser.parseFromString` sanitization instances. At some point it ends but I believe the browser is doing it. If I try it in Chrome, it never ends and hangs the tab.

![tt](https://github.com/user-attachments/assets/b4b39a8d-05ed-48bc-a17b-141c05b63568)

#### Expected output

Expected a TrustedHTML object.

**Comment by koto** [comment]
DOMPurify [initializes itself on import](https://github.com/cure53/DOMPurify/blob/f93acffc37667f7e6a008d7396c961beba831c92/src/purify.ts#L1678), and at that time the polyfill isn't installed yet, so it indeed doesn't create a policy, and is using regular DOM sinks, which triggers an infinite loop from the default policy.

The solution is likely to import DOMPurify once the polyfill is installed (e.g. with a [dynamic import](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/import)).

**Comment by orazioedoardo** [comment]
Thank you very much, your reply headed me to the right direction, here's the solution for future readers:

```
import { trustedTypes, TrustedTypeConfig, TrustedTypesEnforcer } from "trusted-types";

if (!window.trustedTypes || !window.trustedTypes.createPolicy) {
    window.trustedTypes = trustedTypes;
    const config = new TrustedTypeConfig(false, true, ["default", "dompurify"], false);
    const enforcer = new TrustedTypesEnforcer(config);
    enforcer.install();
}

const DOMPurifyProfile = {
    RETURN_TRUSTED_TYPE: false,
    USE_PROFILES: {
        html: true
    }
}

import("dompurify").then(({ default: DOMPurify }) => {
    window.trustedTypes.createPolicy("default", {
        createHTML: (string, type) => {
            const sanitized = DOMPurify.sanitize(string, { RETURN_TRUSTED_TYPE: false });
            console.warn("Created a '" + type + "' object.")
            return sanitized;
        }
    });
});
```

Unfortunately webpack would load dompurify from a chunk but since the URL is not a `TrustedScriptURL` the import would fail. I tried creating a default policy with the `createScriptURL` and the module loaded but then I couldn't add other policies because duplicates are not allowed. Chicken and egg problem. To get out of it I simply disabled chunks in webpack, which I prefer anyway:

```
const webpack = require('webpack');
module.exports = {
  // ...
  plugins: [
    new webpack.optimize.LimitChunkCountPlugin({
      maxChunks: 1,
    }),
  ],
};
```
