### ISSUE TITLE
Add tests for worker constructors called from worker global scope

### ISSUE THREAD

**Issue by fred-wang** [w3c/trusted-types#567]
https://html.spec.whatwg.org/multipage/workers.html#dedicated-workers-and-the-worker-interface
https://html.spec.whatwg.org/multipage/workers.html#shared-workers-and-the-sharedworker-interface

We have `trusted-types/worker-constructor.https.html` for worker constructors, but IIUC all the `new` calls are done from the Window global scope.

cc @mbrodesser-Igalia @lukewarlow

**Comment by mbrodesser-Igalia** [comment]
SharedWorker is only exposed to Window, see the IDL definition of https://html.spec.whatwg.org/multipage/workers.html#shared-workers-and-the-sharedworker-interface. So only tests for Workers are required.

**Comment by mbrodesser-Igalia** [comment]
Fixed via above linked commit.

**Comment by fred-wang** [comment]
> SharedWorker is only exposed to Window, see the IDL definition of https://html.spec.whatwg.org/multipage/workers.html#shared-workers-and-the-sharedworker-interface. So only tests for Workers are required.

Sorry, I opened this issue quickly and I think I was not very clear. I meant covering each worker scope, not covering each worker constructor. The Worker constructor is exposed to Window, DedicatedWorker, SharedWorker. Your patch added the DedicatedWorker case, but we are still lacking the SharedWorker case. Doing that in https://github.com/web-platform-tests/wpt/pull/50017
